name: wikib_providers
description: A simple command-line application.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies:
  azure:
    path: ../azure
  hive:
  rewise_storage:
    path: ../rewise_storage
  riverpod: 2.0.0-dev.5
  azure_storage:
    path: ../azure_storage
  utils:
    path: ../utils 

dev_dependencies:
  test:
