name: webview_lib
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  audioplayers: 1.0.0-rc.2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_hooks:
  flutter_inappwebview:
  freezed_annotation: 
  functional_widget_annotation:
  hooks_riverpod: 2.0.0-dev.7
  js:
  json_annotation:
  permission_handler:
  utils:
    path: ../utils 
  webview_windows:
    # path: d:/github/flutter-webview-windows

dev_dependencies:
  build_runner: 
  freezed:
  functional_widget: 
  json_serializable:
  test:

flutter:
  uses-material-design: true

  assets:
   - assets/index.html
   - assets/media.js
