name: media3
publish_to: 'none' 
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cupertino_icons:
  flutter:
    sdk: flutter
  flutter_hooks:
  flutter_inappwebview:
  functional_widget_annotation:
  hooks_riverpod: 2.0.0-dev.7
  json_annotation:
  permission_handler:
  url_launcher:
  utils:
    path: ../utils 

dependency_overrides:

dev_dependencies:
  build_runner: 
  functional_widget: 
  json_serializable:
  test:

flutter:
  uses-material-design: true

  assets:
   - assets/index.html
