name: localization
description: localization
version: 1.0.0
publish_to: 'none' 

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies:
  analyzer: ^3.3.0
  path:
  protobuf_for_dart:
    path: ../../../wikibulary/shared/protobufs/protobuf_for_dart
  tuple:

