name: localization
description: localization
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies:
  analyzer: ^3.3.0
  protobuf_for_dart: ^0.9.0
  path:
  tuple:

