name: rewise_storage
description: A simple command-line application.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies:
  azure:
    path: ../azure 
  azure_storage:
    path: ../azure_storage  
  # flutter:
  #  sdk: flutter
  hive: 
  protobuf:
  protobuf_for_dart:
    path: ../../../wikibulary/shared/protobufs/protobuf_for_dart
  riverpod: 2.0.0-dev.6
  utils:
    path: ../utils 

dev_dependencies:
  build_runner: 
  hive_generator:
  test:
