name: rewise_storage
description: A simple command-line application.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies:
  azure:
    path: ../azure  
  flutter:
    sdk: flutter
  utils:
    path: ../utils 

dev_dependencies:
  lints: ^1.0.0
