name: azure_storage
description: A simple command-line application.
version: 1.0.0
publish_to: 'none'

# homepage: https://www.example.com

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies:
  azure:
    path: ../azure 
  hive:
  riverpod:
  utils:
    path: ../utils 

dev_dependencies:
  test:
  hive_generator:
  build_runner: 
