name: media
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  audio_session:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_hooks:
  flutter_sound:
  flutter_sound_platform_interface:
  freezed_annotation: 
  functional_widget_annotation:
  permission_handler:
  riverpod:

dev_dependencies:
  build_runner: 
  freezed:
  functional_widget: 
  test:

flutter:
  uses-material-design: true
