name: media
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  audioplayers: 1.0.0-rc.2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_hooks:
  freezed_annotation: 
  functional_widget_annotation:
  hooks_riverpod: 2.0.0-dev.5
  # permission_handler:
  utils:
    path: ../utils 
  webview_windows:

dependency_overrides:
  audioplayers_web:
    path: ../../../github/audioplayers/packages/audioplayers_web

dev_dependencies:
  build_runner: 
  freezed:
  functional_widget: 
  test:

flutter:
  uses-material-design: true
