name: azure
description: A simple command-line application.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  crypto:
  # flutter:
  #  sdk: flutter
  hive:
  http:
  protobuf:
  protobuf_for_dart:
    path: ../../../wikibulary/shared/protobufs/protobuf_for_dart
  riverpod:
  tuple:
  utils:
    path: ../utils 

dev_dependencies:
  hive_generator:
  build_runner: 
  test: 
