name: media2
publish_to: 'none' 
version: 1.0.0

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_hooks:
  freezed_annotation: 
  functional_widget_annotation:
  hooks_riverpod: 2.0.0-dev.5
  just_audio:
  record:
  # just_audio_libwinmedia:
  utils:
    path: ../utils 
  webview_windows:

dependency_overrides:

dev_dependencies:
  build_runner: 
  freezed:
  functional_widget: 
  test:

flutter:
  uses-material-design: true
