// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      // LM hack
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        return web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB0wkt-YZ9UtXmLSKFZttA_Fjeo3FhVHM',
    appId: '1:254440128982:web:f704ae353e7dbc07f4e477',
    messagingSenderId: '254440128982',
    projectId: 'wikibulary-1589552057434',
    authDomain: 'wikibulary-1589552057434.firebaseapp.com',
    storageBucket: 'wikibulary-1589552057434.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQuhh533vR_aSbhvPE7Ti2vglb32IUOY0',
    appId: '1:254440128982:android:3f77eab59b8157f3f4e477',
    messagingSenderId: '254440128982',
    projectId: 'wikibulary-1589552057434',
    storageBucket: 'wikibulary-1589552057434.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDPSfKOMhmfRYRVEiZTYwc5xBQeeOfdf0',
    appId: '1:254440128982:ios:3f74e18b134901b5f4e477',
    messagingSenderId: '254440128982',
    projectId: 'wikibulary-1589552057434',
    storageBucket: 'wikibulary-1589552057434.appspot.com',
    iosClientId: '254440128982-81t4sn6q5ogeiio357oj8pui3ktmqchu.apps.googleusercontent.com',
    iosBundleId: 'io.invertase.flutter.desktopWebviewAuthExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDPSfKOMhmfRYRVEiZTYwc5xBQeeOfdf0',
    appId: '1:254440128982:ios:3f74e18b134901b5f4e477',
    messagingSenderId: '254440128982',
    projectId: 'wikibulary-1589552057434',
    storageBucket: 'wikibulary-1589552057434.appspot.com',
    iosClientId: '254440128982-81t4sn6q5ogeiio357oj8pui3ktmqchu.apps.googleusercontent.com',
    iosBundleId: 'io.invertase.flutter.desktopWebviewAuthExample',
  );
}
