name: utils
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies:
  # connectivity_plus: ^2.2.1
  flutter:
    sdk: flutter
  http:
  path:
  tuple:

dev_dependencies:
